server:
  port: 8087

spring:
  application:
    name: w2m-virtual-d5-scoring-api
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest

scoring:
  topic: bookings.events
  payments-topic: payments.events

hotels:
  topic: hotels.events

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    com.w2m.virtual.d5scoring: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
